project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "Todd Schoellman"
  site-url: https://toddschoellman.com
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: research.qmd
        text: Research
      - href: personal.qmd
        text: Personal
  page-footer:
    left: "Â© 2026 Todd Schoellman"
    right: "Last updated: February 2026"

format:
  html:
    theme: litera
    fontsize: 1.05em
    css: styles.css
    link-external-newwindow: true